public class Person {
    public static void main(String[] args) {
        System.out.println("ssss");
        System.out.println("dsadasdasfas");
        System.out.println("maind");
        System.out.println("daewwqwrrfsadsafas");
        System.out.println("jhgghfh");
        System.out.println("ddddd");
        System.out.println("dsad");
        System.out.println("dsaddhnvbnvc");
        System.out.println("dsaddhnvbnvc");
        System.out.println("dsaddhnvbnvc");
        System.out.println("dsaddhnvbnvc");
        System.out.println("mearge");
        System.out.println("dsadas");
        System.out.println("mergemerge");
        System.out.println("dsaddhnvbnvc");
        System.out.println("dsaddhnvbnvc");
        System.out.println("dsaddhnvbnvc");
        System.out.println("dsaddhnvbnvc");
        System.out.println("mearge");
        System.out.println("dsadas");
        System.out.println("mergemerge");
        System.out.println("dsaddhnvbnvc");
        System.out.println("dsaddhnvbnvc");
        System.out.println("dsaddhnvbnvc");
        System.out.println("dsaddhnvbnvc");
        System.out.println("mearge");
        System.out.println("dsadas");
        System.out.println("mergemerge");
    }
}